package pl.projewski.bitcoin.exchange.binance.api.v1;

public enum FilterType {
    PRICE_FILTER, LOT_SIZE, MIN_NOTIONAL, ICEBERG_PARTS, MAX_NUM_ALGO_ORDERS, MAX_NUM_ORDERS, PERCENT_PRICE, MARKET_LOT_SIZE, TRAILING_DELTA, MAX_POSITION;
}
