package pl.projewski.bitcoin.exchange.bitbay.api.rest.model;

public enum Error {
    ACTION_BLOCKED,
    ACTION_LIMIT_EXCEEDED,
    INVALID_HASH_SIGNATURE,
    INVALID_OPERATION_ID,
    INVALID_REQUEST,
    MARKET_NOT_RECOGNIZED,
    OFFER_FUNDS_NOT_EXCEEDING_MINIMUMS,
    OFFER_WOULD_HAVE_BEEN_PARTIALLY_FILLED,
    PERMISSIONS_NOT_SUFFICIENT,
    REQUEST_TIMESTAMP_INVALID_FORMAT,
    REQUEST_TIMESTAMP_TOO_OLD,
    RESPONSE_TIMEOUT,
    TIMEOUT,
    UNDER_MAINTENANCE;
}
